#! /bin/sh
#
# Create device nodes required by cvsfs
#
# This script have only to be executed if the device file system (devfsd)
# is not in use !
#
# Execute the script as root
#
if [ -e "/dev/.devfsd" ]; then
    echo "You are using the device file system - skipped."
else
    rm -rf /dev/cvsfs
    mkdir -m 0700 /dev/cvsfs
    let x=0
    while [ $x -le 255 ]; do
	/bin/mknod --mode=0600 /dev/cvsfs/$x c 245 $x
	let x=x+1
    done
fi
